version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=grupox
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=proyectoBDD
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1234
      MYSQL_DATABASE: proyectoBDD
