FROM mysql:latest

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpass1234
ENV MYSQL_DATABASE=proyectoBDD

# Scripts SQL para inicializar la base de datos
COPY ./sql-scripts/ /docker-entrypoint-initdb.d/

EXPOSE 3306
