version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=grupox
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=proyectoBDD
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    command: ng serve --open

mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1234
      MYSQL_DATABASE: proyectoBDD
    depends_on:
      - backend 
    volumes:
      - ./init_database.sql:/docker-entrypoint-initdb.d/init_database.sql

