# Usar una imagen base de Node.js
FROM node:latest

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código fuente del backend al contenedor
COPY Backend /app
COPY package*.json ./
COPY .npmrc ./

# Copia los archivos de la aplicación necesarios para la instalación de dependencias


# Instalar las dependencias del backend
RUN npm install

# Puerto en el que escucha el servidor Express
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
