FROM mysql:latest

# Variables de entorno para configurar la base de datos
ENV MYSQL_ROOT_PASSWORD=rootpass1234
ENV MYSQL_DATABASE=proyectoBDD

# Copiar el script SQL al directorio de inicialización de la base de datos
COPY ./init_database.sql /docker-entrypoint-initdb.d/

EXPOSE 3306